import Head from "next/head";
import Image from "next/image";
import Agenda from "../components/agenda";
import TwitterGraphics from "../components/didYouKnow";
import EngageSocials from "../components/engageSocials";
import MetaGraphics from "../components/fbAndIg";
import KeyTweets from "../components/keyTweets";
import Navbar from "../components/navbar";
import Partners from "../components/partners";
import Speakers from "../components/speakers";
import TweetCard from "../components/tweetCard";
import Videos from "../components/videos";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <body className="has-navbar-fixed-top"></body>
      </Head>
      <Navbar />
      <main className="container is-fullhd">
        <section className="hero is-medium is-danger">
          <div className="hero-body">
            <p className="is-size-1 has-text-centered has-font-weight-bold">Social Media Kit</p>
            <p className="subtitle has-text-centered">Home/Social Media Kit</p>
          </div>
        </section>
        <section className="section">
          <article className="has-text-centered">
            <p className="is-size-2 has-text-black  has-font-weight-medium">
              African Health Economics &#38; Policy Association Conference 2022
            </p>
            <p className="is-size-4 has-text-black has-font-weight-medium">
              Decade for Action: Driving Momentum to Achieve #UHCInAfrica
            </p>
            <p className="is-size-5 has-text-black">8th – 10th March 2021</p>
            <p className="is-size-5 has-text-black">14:00 - 1800 EAT</p>
          </article>
        </section>
        <EngageSocials />
        <div className="container is-fullhd has-background-light">
          <Agenda />
        </div>
        <div className="container is-fullhd has-background-light">
         <Speakers/>
        </div>
        <div className="container is-fullhd">
        <Partners/>
        </div>
        <div className="container is-fullhd">
        <TwitterGraphics/>
        </div>
        <div className="container is-fullhd">
       <MetaGraphics/>
        </div>
        <div className="container is-fullhd">
          <Videos />
        </div>
        <div className="container is-fullhd">
          <KeyTweets/>
        </div>
      </main>
    </div>
  );
}
